# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DsR0iMdXrYE22lnoyvIq7blz59VVMlyP
"""

import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from PIL import Image
import argparse
from torchvision import transforms
from torchvision.datasets import FashionMNIST # Added for context, though not strictly needed for this cell's error fix

# FIX: Changed LATENT_DIM from 32 to 2 to match the saved model
LATENT_DIM = 2


class Autoencoder(nn.Module):

    def __init__(self, latent_dim):
        super().__init__()

        self.encoder = nn.Sequential(
            nn.Flatten(),
            nn.Linear(784, 256),
            nn.ReLU(),
            nn.Linear(256, latent_dim)
        )

        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, 256),
            nn.ReLU(),
            nn.Linear(256, 784),
            nn.Sigmoid()
        )

    def forward(self, x):
        z = self.encoder(x)
        x = self.decoder(z)
        return x.view(-1, 1, 28, 28)


parser = argparse.ArgumentParser()

parser.add_argument(
    "--model",
    type=str,
    required=True
)

# FIX: Pass arguments explicitly for Colab environment.
# The model was saved to '/content/autoencoder_2.pth' in the previous step.
args = parser.parse_args(["--model", "/content/autoencoder_2.pth"])

device = torch.device("cpu")

model = Autoencoder(LATENT_DIM)

model.load_state_dict(
    torch.load(args.model, map_location=device)
)

model.eval()

with torch.no_grad():

    z = torch.randn(1, LATENT_DIM)

    generated = model.decoder(z)

    generated = generated.view(28, 28).numpy()

Image.fromarray(
    (generated * 255).astype("uint8")
).save("generated_image.png")

plt.imshow(generated, cmap="gray")
plt.axis("off")
plt.show()

print("generated_image.png berhasil dibuat")