# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DsR0iMdXrYE22lnoyvIq7blz59VVMlyP
"""

import torch
import torch.nn as nn

from torchvision import transforms
from torchvision.datasets import FashionMNIST

from PIL import Image
import argparse
import matplotlib.pyplot as plt


LATENT_DIM = 2


class Autoencoder(nn.Module):

    def __init__(self, latent_dim):
        super().__init__()

        self.encoder = nn.Sequential(
            nn.Flatten(),
            nn.Linear(784, 256),
            nn.ReLU(),
            nn.Linear(256, latent_dim)
        )

        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, 256),
            nn.ReLU(),
            nn.Linear(256, 784),
            nn.Sigmoid()
        )

    def forward(self, x):
        z = self.encoder(x)
        x = self.decoder(z)
        return x.view(-1, 1, 28, 28)


parser = argparse.ArgumentParser()

parser.add_argument(
    "--model",
    type=str,
    required=True,
    help="Path file model .pth"
)

parser.add_argument(
    "--index",
    type=int,
    default=0,
    help="Index gambar Fashion-MNIST"
)

# Fix: Pass arguments explicitly for Colab environment.
# Replace 'path/to/your/model.pth' with the actual path to your model file.
args = parser.parse_args(["--model", "/content/autoencoder_2.pth"])


device = torch.device("cpu")

model = Autoencoder(LATENT_DIM)

model.load_state_dict(
    torch.load(args.model, map_location=device)
)

model.eval()


dataset = FashionMNIST(
    root="./data",
    train=False,
    download=True,
    transform=transforms.ToTensor()
)

image, _ = dataset[args.index]

with torch.no_grad():
    reconstructed = model(
        image.unsqueeze(0)
    )

original = image.squeeze().numpy()
reconstructed = reconstructed.squeeze().numpy()

Image.fromarray(
    (original * 255).astype("uint8")
).save("original.png")

Image.fromarray(
    (reconstructed * 255).astype("uint8")
).save("reconstructed.png")


plt.figure(figsize=(8, 4))

plt.subplot(1, 2, 1)
plt.imshow(original, cmap="gray")
plt.title("Original")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(reconstructed, cmap="gray")
plt.title("Reconstructed")
plt.axis("off")

plt.tight_layout()
plt.savefig("comparison.png")

print("Berhasil!")
print("File yang dihasilkan:")
print("- original.png")
print("- reconstructed.png")
print("- comparison.png")

"""### Latih Autoencoder (jika model tidak tersedia)"""

from torch.utils.data import DataLoader

# Hyperparameters
NUM_EPOCHS = 5
BATCH_SIZE = 64
LEARNING_RATE = 1e-3

# Load FashionMNIST training data
train_dataset = FashionMNIST(
    root='./data',
    train=True,
    download=True,
    transform=transforms.ToTensor()
)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

# Initialize model, loss function, and optimizer
model_train = Autoencoder(LATENT_DIM).to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model_train.parameters(), lr=LEARNING_RATE)

print("Memulai pelatihan Autoencoder...")

# Training loop
for epoch in range(NUM_EPOCHS):
    for batch_idx, (data, _) in enumerate(train_loader):
        data = data.to(device)

        # Forward pass
        output = model_train(data)
        loss = criterion(output, data)

        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (batch_idx+1) % 100 == 0:
            print(f'Epoch [{epoch+1}/{NUM_EPOCHS}], Step [{batch_idx+1}/{len(train_loader)}], Loss: {loss.item():.4f}')

print("Pelatihan selesai.")

# Save the trained model
SAVE_MODEL_PATH = args.model
torch.save(model_train.state_dict(), SAVE_MODEL_PATH)
print(f"Model disimpan ke: {SAVE_MODEL_PATH}")